# Generated by Django 6.0.3 on 2026-03-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_country"),
        ("recipes", "0003_recipe_photo_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="origin_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="social.country",
            ),
        ),
    ]

