# Generated by Django 6.0.3 on 2026-03-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="photo_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
