# Generated by Django 6.0.3 on 2026-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iso2",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 code (e.g. US).",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "map_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional map library code override.",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
